// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI5mPRY5_fJMUUoqSPROFuHCuBEN1yEFY',
    appId: '1:749234946339:web:2f21ec520c22de7e4b4c96',
    messagingSenderId: '749234946339',
    projectId: 'flutter-app-c118d',
    authDomain: 'flutter-app-c118d.firebaseapp.com',
    storageBucket: 'flutter-app-c118d.firebasestorage.app',
    measurementId: 'G-ZHHNRY403W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjIfoOg-8KlJ-LDCOfeCdVK916ZWeUXN4',
    appId: '1:749234946339:android:445487da109f82a14b4c96',
    messagingSenderId: '749234946339',
    projectId: 'flutter-app-c118d',
    storageBucket: 'flutter-app-c118d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-jzOX0UaFMWmfcxDFVtHE5lwpdkoj6IQ',
    appId: '1:749234946339:ios:cffddae0469f057b4b4c96',
    messagingSenderId: '749234946339',
    projectId: 'flutter-app-c118d',
    storageBucket: 'flutter-app-c118d.firebasestorage.app',
    iosBundleId: 'com.example.socialAppClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-jzOX0UaFMWmfcxDFVtHE5lwpdkoj6IQ',
    appId: '1:749234946339:ios:cffddae0469f057b4b4c96',
    messagingSenderId: '749234946339',
    projectId: 'flutter-app-c118d',
    storageBucket: 'flutter-app-c118d.firebasestorage.app',
    iosBundleId: 'com.example.socialAppClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI5mPRY5_fJMUUoqSPROFuHCuBEN1yEFY',
    appId: '1:749234946339:web:1adadebffb0f40ca4b4c96',
    messagingSenderId: '749234946339',
    projectId: 'flutter-app-c118d',
    authDomain: 'flutter-app-c118d.firebaseapp.com',
    storageBucket: 'flutter-app-c118d.firebasestorage.app',
    measurementId: 'G-NGVJ93VLBS',
  );
}
